package Model;

public enum EduStages {
    KARDANI,
    KARSHENASI_NAPEYVASTEH,
    KARSHENASI_PEYVASTEH,
    KARSHENASI_ARSHAD_PEYVASTEH,
    KARSHENASI_ARSHAD_NAPEYVASTEH,
    DOCTORAYE_HERFEYI,
    DOCTORAYE_PEYVASTEH,
    DOCTORAYE_TAKHASOSI_NAPEYVASTEH
}
