package Model;

import java.util.EnumSet;

public enum EduStages {
    KARDANI, KARSHENASI_NAPEYVASTEH, KARSHENASI_PEYVASTEH,
    KARSHENASI_ARSHAD_PEYVASTEH, KARSHENASI_ARSHAD_NAPEYVASTEH, DOCTORAYE_HERFEYI, DOCTORAYE_PEYVASTEH
    , DOCTORAYE_TAKHASOSI_NAPEYVASTEH;
    public static EnumSet<EduStages> level1 = EnumSet.of(KARDANI, KARSHENASI_NAPEYVASTEH, KARSHENASI_PEYVASTEH);
    public static EnumSet<EduStages> level2 = EnumSet.of(KARSHENASI_ARSHAD_PEYVASTEH, KARSHENASI_ARSHAD_NAPEYVASTEH, DOCTORAYE_HERFEYI, DOCTORAYE_PEYVASTEH);
    public static EnumSet<EduStages> level3 = EnumSet.of(DOCTORAYE_TAKHASOSI_NAPEYVASTEH);
}
